### ISSUE TITLE
Parse transforms will be deprecated in a future Elixir version

### ISSUE THREAD

**Issue by seancribbs** [Quviq/eqc_ex#10]
My test here https://github.com/Comcast/statefilex/blob/master/test/state_file_test.exs issues a warning:

```
warning: @compile {:parse_transform, _} is deprecated. Elixir will no longer support Erlang-based transforms in future versions
```

This will have to be replaced with Elixir macros, or disabled for Elixir-based tests.

**Comment by ThomasArts** [comment]
Thanks Sean. I am aware of it, but I fear we will have a hard time to replace parse transforms for Elixir by macros, given the little commercial benefit we get from the Elixir version of QuickCheck. Most likely we will ask people to write their models in the new formalism manually instead.
