### ISSUE TITLE
Publish eqc_ex 1.3.0 to Hex.pm

### ISSUE THREAD

**Issue by gausby** [Quviq/eqc_ex#5]
It seems that a new release has been prepared, and should get published when Elixir 1.3 was released. Elixir 1.3 has been released but the newest version on hex.pm is still 1.2.4.

**Comment by ThomasArts** [comment]
Yes, holiday season... you can use the github one, will push to hex after holidays

**Comment by gausby** [comment]
Fair enough. Have a nice holiday!

**Comment by ThomasArts** [comment]
Version 1.3 for eqc_ex is now online! Including documentation.
