### ISSUE TITLE
Testing converging state

### ISSUE THREAD

**Issue by timbuchwaldt** [Quviq/eqc_ex#9]
Heya,
I just got started introducing `eqc_ex` into a project and wanted to test some state that converges after some time (a DB update in a `Task`).
I understand `timeout/2` allows to specify an upper time bound on a property, but I was not able to find a way of expressing "this `ensure` should become and stay true in the next x ms".

Is this just a stupid assumption/idea to test in this way or would it be possible to support such a test in QuickCheck?

**Comment by nickelization** [comment]
@timbuchwaldt that's a great idea, and I've actually seen and used that test strategy to great success in Riak. It's a pretty solid way to test eventually consistent operations, when you know something may not complete right away, but should complete within a reasonable amount of time.

I don't know of any native support for this kind of testing in EQC, but it's pretty easy to write your own utility function for this kind of test. Something like:
```
def wait_until(expected_value, retries \\ 0) do
  result = do_test()
  if result == expected_value do
    true
  else
    if retries > @max_retries do
      IO.puts "test failed"
      false
    else
      Process.sleep(@retry_time)
      wait_until(expected_value, retries + 1)
    end
  end
end
```
Haven't tested the above code at all, but something along those lines should work. Would certainly be cool if there were some sort of native EQC macro for this kind of thing though :)

**Comment by ThomasArts** [comment]
You can either sleep for a while and check that it happened, or poll for it.

The first makes testing slow, the second is faster if the operation normally is fast, but sometimes takes a bit of time.
